.travis.yml
Adding postgres database called H2MSDatabase to travis. I tested Michael's changes with this and they passed travis's build.
=> Adding postgres

.travis.yml
Using createdb instead. This was actually able to create the database with Michael's changes.
=> Creating postgres database with createdb instead.

frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/privacy/privacy.component.css, frontend/src/app/privacy/privacy.component.html, frontend/src/app/privacy/privacy.component.ts
Adding a privacy policy for the H2MS app. Includes a new Privacy component.
=> Adding privacy policy at /privacy route.

frontend/.angular-cli.json, frontend/src/app/app-routing.module.ts, frontend/src/app/login/login.component.css, frontend/src/app/login/login.component.html, frontend/src/app/privacy/privacy.component.html, frontend/src/theme.scss
- Angular Material custom color theme added
- Privacy linked from Login page
=> Frontend theme and privacy link

src/main/java/edu/harvard/h2ms/domain/core/Location.java, src/main/java/edu/harvard/h2ms/repository/LocationRepository.java, src/test/java/edu/harvard/h2ms/web/init/LocationRestTest.java
Add the unit test noted in the JIRA for the location read api.
=> Added Unit Tests - Location API

buildrun.ps1, docker-compose.yml, frontend/.dockerignore, frontend/Dockerfile, frontend/nginx-custom.conf, src/main/resources/application-docker.properties
This adds a container for frontend, and adds it to docker-compose. Need this to get jenkins to auto deploy the front end too.
=> Front end docker container

frontend/src/app/app-routing.module.ts, frontend/src/app/sidenav/sidenav.component.html
* Adding Observe to the SideNav menu
* Small bug fix. Dark grey is now applied to sidenav elements that don't have nested sub navigation items.
=> Adding Observe to the SideNav menu

frontend/package-lock.json, frontend/package.json, frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/export/export.component.html, frontend/src/app/export/export.component.ts
Adds a new 'export' component, which displays a screen with a button to begin a download of the csv data. Also adds a dependency for file-saver to facilitate local saving of the file.
TODO still: needs to use the real API endpoint for getting the file, and needs authentication headers added to the request. Menu needs to filter out the export option on mobile.
=> Add Export pages and menu item for exporting a csv.

src/main/java/edu/harvard/h2ms/seeders/HandwashEventTemplateSeeder.java
I built this originally off the earlier version of the wireframes.
- Opportunity checkbox shouldn't exist
- Relative moment fields are entering, inside, leaving not "Room Entry", "Room Exit"
=> Handwashing event template should match wireframes

frontend/src/app/auth/auth.service.ts, frontend/src/app/config/config.service.ts, frontend/src/app/config/config.ts, frontend/src/app/config/gloves-config.ts, frontend/src/app/config/h2ms-config.ts, frontend/src/app/login/login.component.html
- added backend auth port to config
=> frontend live site backend port number in config

frontend/src/app/config/config.ts, frontend/src/app/login/login.component.css, frontend/src/app/reports/reports.component.ts, frontend/src/app/reports/reports.service.ts
- updated report component to use config
- disabled fake data for demo
- cleaned up unnecessary comments in reports component
- removed login card spacing
- style: changed some double quotes to single quotes
=> Frontend-reports-config

frontend/src/app/app.module.ts, frontend/src/app/dynamic-form-question/dynamic-form-question.component.html, frontend/src/app/dynamic-form/dynamic-form.component.html, frontend/src/app/dynamic-form/dynamic-form.component.ts, frontend/src/app/dynamic-form/form-submission-dialog.html, frontend/src/app/event/event.component.css, frontend/src/app/event/event.component.html
- popup on observation submit
- color theme on checkbox on observe form
=> Frontend event popup and color theming

frontend/src/app/dynamic-form-question/dynamic-form-question.component.html, frontend/src/app/dynamic-form/dynamic-form.component.html
Frontend event page Angular Material drop downs swapped in for a cleaner look
=> Frontend event page Angular Material drop downs

frontend/src/app/dynamic-form/form-submission-dialog.html
I made the dialog Ok button blue.
=> Changing dialog Ok button to be blue and raised.

frontend/src/app/app.component.ts, frontend/src/app/sidenav/sidenav.component.ts, frontend/src/index.html
=> Frontend-tab-title

frontend/src/app/about/about.component.css, frontend/src/app/about/about.component.html, frontend/src/app/about/about.component.ts, frontend/src/app/app.component.ts, frontend/src/app/card.css, frontend/src/app/dynamic-form-question/dynamic-form-question.component.css, frontend/src/app/dynamic-form-question/dynamic-form-question.component.html, frontend/src/app/dynamic-form-question/dynamic-form-question.component.ts, frontend/src/app/dynamic-form/dynamic-form.component.html, frontend/src/app/dynamic-form/dynamic-form.component.ts, frontend/src/app/event/event.component.css, frontend/src/app/event/event.component.html, frontend/src/app/event/event.component.ts, frontend/src/app/export/export.component.css, frontend/src/app/export/export.component.html, frontend/src/app/export/export.component.ts, frontend/src/app/login/login.component.css, frontend/src/app/login/login.component.html, frontend/src/app/login/login.component.ts, frontend/src/app/privacy/privacy.component.html, frontend/src/app/privacy/privacy.component.ts, frontend/src/app/reports/reports.component.css, frontend/src/app/reports/reports.component.html, frontend/src/app/reports/reports.component.ts
Switching the event form to use material labels (which have a required asterisk) and adjusting the form width to use the same min-width as google forms.
=> Switch Event Form To Material Labels and Adjust Form Width

frontend/src/app/app.module.ts, frontend/src/app/dynamic-form/dynamic-form.component.ts, frontend/src/app/login/login.component.ts, frontend/src/app/user/service/user-email.service.ts
- create service for email storage/retrieval
=> Frontend-store-email

src/main/java/edu/harvard/h2ms/web/controller/NotificationController.java, src/test/java/edu/harvard/h2ms/controllers/NotificationControllerTests.java
fixed typo (notificaiton to notification)
=> fixed typo (notificaiton to notification)

src/main/java/edu/harvard/h2ms/repository/AnswerRepository.java, src/main/java/edu/harvard/h2ms/repository/EventRepository.java, src/main/java/edu/harvard/h2ms/repository/EventTemplateRepository.java, src/main/java/edu/harvard/h2ms/repository/LocationRepository.java, src/main/java/edu/harvard/h2ms/repository/NotificationRepository.java, src/main/java/edu/harvard/h2ms/repository/QuestionRepository.java, src/main/java/edu/harvard/h2ms/repository/RoleRepository.java, src/main/java/edu/harvard/h2ms/repository/UserRepository.java
This fixes all the automatic search generated API endpoints.
=> Add parameters to service types so automatic endpoints work

frontend/src/app/app.component.html
Removing the orange toggle config button for the demo. Just commenting it out in the HTML. Will re-enable after demo but before faculty panel.
=> * Disabling the toggle config button for our demo
